openapi: 3.0.0
info:
  title: RingCentral-Engage-Digital-API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/messages/{messageId}':
    parameters:
      - schema:
          type: string
        name: messageId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-messages-messageId
      description: ''
components:
  schemas: {}
