openapi: 3.0.0
info:
  title: RingCentral Officee API
  version: '1.0'
  contact:
    url: 'https://developers.ringcentral.com'
    name: RingCentral Developers
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
